name: realtime_database
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: morrisjdev <morrisj@live.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  web_socket_channel: 1.1.0
  rxdart: 0.22.6
  uuid: 2.0.4
  json_annotation: ^3.0.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
